/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CpuFreqMeter
#define HEADER_CpuFreqMeter
/*
htop - CpuFreqMeter.h
(C) 2018 @lex
*/

#include "Meter.h"

extern int CpuFreqMeter_attributes[];

extern MeterClass CpuFreqMeter_class;

#endif
